<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc862ee0d85c1fa4c4039eab8fd2ecc6d
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Workerman\\' => 10,
        ),
        'P' => 
        array (
            'PHPSocketIO\\' => 12,
        ),
        'C' => 
        array (
            'Channel\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Workerman\\' => 
        array (
            0 => __DIR__ . '/..' . '/workerman/workerman',
        ),
        'PHPSocketIO\\' => 
        array (
            0 => __DIR__ . '/..' . '/workerman/phpsocket.io/src',
        ),
        'Channel\\' => 
        array (
            0 => __DIR__ . '/..' . '/workerman/channel/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc862ee0d85c1fa4c4039eab8fd2ecc6d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc862ee0d85c1fa4c4039eab8fd2ecc6d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc862ee0d85c1fa4c4039eab8fd2ecc6d::$classMap;

        }, null, ClassLoader::class);
    }
}
