<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'workerman/channel' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../workerman/channel',
            'aliases' => array(),
            'reference' => '3df772d0d20d4cebfcfd621c33d1a1ab732db523',
            'dev_requirement' => false,
        ),
        'workerman/phpsocket.io' => array(
            'pretty_version' => 'v1.1.14',
            'version' => '1.1.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../workerman/phpsocket.io',
            'aliases' => array(),
            'reference' => 'a5758da4d55b4744a4cc9c956816d88ce385601e',
            'dev_requirement' => false,
        ),
        'workerman/workerman' => array(
            'pretty_version' => 'v4.1.4',
            'version' => '4.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../workerman/workerman',
            'aliases' => array(),
            'reference' => '83e007acf936e2233ac92d7368b87716f2bae338',
            'dev_requirement' => false,
        ),
    ),
);
